### ISSUE TITLE
ModuleNotFoundError: No module named 'urlparse'

### ISSUE THREAD

**Issue by AbhilashPal** [banglakit/corpus-builder#14]
Trying to run the parser but running into the above error. All dependencies are solved. Using Python 3.7 with conda.

**Comment by aniruddha-adhikary** [comment]
@AbhilashPal would you please paste the complete stack trace?

**Comment by aniruddha-adhikary** [comment]
Please use Python 2.7.x to use this.

**Comment by AbhilashPal** [comment]
(base) D:\Machine Learning\Paper\BanglaOCR\corpus-builder>scrapy crawl bangladesh_pratidin -a start_date='2016-06-01' -a end_date='2016-06-05' -o test3.csv
Traceback (most recent call last):
  File "c:\miniconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\miniconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Miniconda\Scripts\scrapy.exe\__main__.py", line 9, in <module>
  File "c:\miniconda\lib\site-packages\scrapy\cmdline.py", line 149, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "c:\miniconda\lib\site-packages\scrapy\crawler.py", line 249, in __init__
    super(CrawlerProcess, self).__init__(settings)
  File "c:\miniconda\lib\site-packages\scrapy\crawler.py", line 137, in __init__
    self.spider_loader = _get_spider_loader(settings)
  File "c:\miniconda\lib\site-packages\scrapy\crawler.py", line 336, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "c:\miniconda\lib\site-packages\scrapy\spiderloader.py", line 61, in from_settings
    return cls(settings)
  File "c:\miniconda\lib\site-packages\scrapy\spiderloader.py", line 25, in __init__
    self._load_all_spiders()
  File "c:\miniconda\lib\site-packages\scrapy\spiderloader.py", line 47, in _load_all_spiders
    for module in walk_modules(name):
  File "c:\miniconda\lib\site-packages\scrapy\utils\misc.py", line 71, in walk_modules
    submod = import_module(fullpath)
  File "c:\miniconda\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Machine Learning\Paper\BanglaOCR\corpus-builder\corpus_builder\spiders\newspaper\amader_somoy.py", line 3, in <module>
    import urlparse
ModuleNotFoundError: No module named 'urlparse'
